project:
  type: website

website:
  site-url: https://CarlosReyCastro.github.io # URL of the website
  title: "Home"
  favicon: images/favicon.png
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  twitter-card: true # https://quarto.org/docs/websites/website-tools.html#twitter-card
  page-footer: "Made with ❤ and Quarto"
  navbar: 
    right:
      - text: Home
        href: index.qmd
      - CV.qmd
      
format:
  html:
    backgroundcolor: "#ffffff"
    fontcolor: "darkslategray"
    linkcolor: "rgb(221, 112, 105)"
    mainfont: "Source Sans Pro, sans-serif"
#    mainfont: "Gill Sans, sans-serif"
    fontsize: 19px
    theme: 
      light: [journal, styles.scss]

    

