project:
  type: website

website:
  site-url: https://CarlosReyCastro.github.io # URL of the website
  title: "Home"
  favicon: images/favicon.png
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  twitter-card: true # https://quarto.org/docs/websites/website-tools.html#twitter-card
  page-footer: "Made with ❤️ and Quarto"
  navbar:
    right:
      - text: Home
        href: index.qmd
      
format:
  html:
    backgroundcolor: "#f2f2f2"
    theme: [journal, styles.scss]

